name: 'Nexus IQ Scan'
description: 'Scan repository for vulnerabilities fail on HIGH'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  app-name:  # name of application / repo
    description: 'The application to scan - name should correspond with repo name'
    required: true
    default: 'test-app'
outputs:
  scan-result: # JSON object representation of the scan result from Nexus IQ
    description: 'Nexus IQ Scan results'
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'node12'
  main: 'dist/index.js'
