name: CI

on: 
  push:
    branches: test/*
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      
      # test external access to action at runtime
      - name: External hello world test
        id: exthello
        uses: i-marsh/priceline-nexus-action@v0.2
        with:
          who-to-greet: 'Ian the RoadWarrior'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The externally calculated time was ${{ steps.exthello.outputs.time }}"
